name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install pandas numpy scikit-learn mlflow

      - name: Run MLflow Project
        run: |
          cd Membangun_Model
          export MLFLOW_ALLOW_FILE_STORE=true
          mlflow run . --env-manager local